version: '3'

networks:
  default:
    driver: bridge

services:

  mariadb:
    image: mariadb:10.2
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
      - MYSQL_DATABASE=yii2advanced
    volumes:
      - ./docker/mariadb/data:/var/lib/mysql
      - ./docker/mariadb/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./docker/mariadb/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - "3306:3306"
    networks:
      - default

  admin:
    build:
      context: ./docker/php-fpm
      args:
        - INSTALL_XDEBUG=true
    volumes:
      - ./sources/app:/var/www:cached
    depends_on:
      - front
    expose:
      - "9000"
    networks:
      - default

  admin_nginx:
    image: nginx:stable
    volumes:
      - ./docker/nginx/sites/backend.conf:/etc/nginx/conf.d/default.conf
      - ./sources/app:/var/www:cached
    working_dir: /var/www
    ports:
      - "11000:80"
    depends_on:
      - admin
    networks:
      - default

  front:
    build:
      context: ./docker/php-fpm
      args:
        - INSTALL_XDEBUG=true
    volumes:
      - ./sources/app:/var/www:cached
    command: sh -c 'composer install; php init --env=Development; php yii migrate --interactive=0; php-fpm'
    depends_on:
      - mariadb
    expose:
      - "9000"
      - "8080"
      - "80"
    networks:
      - default

  front_nginx:
    image: nginx:stable
    volumes:
      - ./docker/nginx/sites/frontend.conf:/etc/nginx/conf.d/default.conf
      - ./sources/app:/var/www:cached
    working_dir: /var/www
    ports:
      - "10000:80"
    depends_on:
      - front
    networks:
      - default
